project:
  type: website
  resources:
    - cv.pdf
    - presentations/ech_sleep_day_final.pdf
    - presentations/gsa_poster_final.pdf
    - presentations/GSA2024_Poster_v1.pdf
    - projects/dashboard.html
    - publications/ecs_evaluation_report.pdf
  output-dir: docs

website:
  title: "Erh-Chi Hsu"
  site-url: https://erhchihsu.github.io/echsu
  description: "Health and Long-Term Care"
  open-graph:
    locale: en_US
  comments:
    utterances:
      repo: erhchihsu/echsu
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
  page-footer:
    left: "© Copyright 2025 Erh-Chi Hsu. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
